name: Trivy Scan on Public Docker Image

on:
  workflow_dispatch:        # Manual trigger
  push:
    branches:
      - main

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Run Trivy Scan on nginx:latest
        uses: aquasecurity/trivy-action@v0.13.1
        with:
          image-ref: 'nginx:latest'              # Replace with any public image
          format: 'sarif'                        # SARIF report format
          output: 'trivy-results.sarif'          # Output file
          exit-code: '1'                         # Fail on CRITICAL/HIGH
          severity: 'CRITICAL,HIGH'

      - name: Upload SARIF Report to GitHub Security
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy-results.sarif

      - name: Upload SARIF as Artifact (Optional)
        uses: actions/upload-artifact@v3
        with:
          name: trivy-scan-report
          path: trivy-results.sarif
