name: Trivy Scan with Logs and Report

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Run Trivy Scan on nginx:latest (Console Output)
        uses: aquasecurity/trivy-action@0.31.0
        with:
          image-ref: 'nginx:latest'
          format: 'table'                 # ✅ Table for human-readable output
          exit-code: '1'                  # ✅ Fail on critical/high
          severity: 'CRITICAL,HIGH'

      - name: Run Trivy Scan on nginx:latest (SARIF Report)
        uses: aquasecurity/trivy-action@0.31.0
        with:
          image-ref: 'nginx:latest'
          format: 'sarif'                 # ✅ Machine-readable SARIF report
          output: 'trivy-results.sarif'
          exit-code: '0'                  # ✅ Do not block on report-only step
          severity: 'CRITICAL,HIGH'

      - name: Upload SARIF Report to GitHub Security
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy-results.sarif

      - name: Upload SARIF as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-report
          path: trivy-results.sarif
