name: Trivy Scan on Public Docker Image

on:
  workflow_dispatch:          # Allows manual trigger
  push:
    branches:
      - main

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Run Trivy Scan on nginx:latest
        uses: aquasecurity/trivy-action@0.31.0        # ✅ Using v0.31.0
        with:
          image-ref: 'nginx:latest'                     # ✅ Public image
          format: 'sarif'                                # ✅ Report in SARIF format
          output: 'trivy-results.sarif'                  # ✅ Output filename
          exit-code: '1'                                 # ✅ Fail on CRITICAL/HIGH
          severity: 'CRITICAL,HIGH'

      - name: Upload SARIF Report to GitHub Security
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy-results.sarif

      - name: Upload SARIF as Artifact
        uses: actions/upload-artifact@v4                # ✅ Fixed to v4
        with:
          name: trivy-scan-report
          path: trivy-results.sarif
